### ISSUE TITLE
Explicit message must be reported OutOfMemory happens and other known failures

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1928] opened 2020-06-26 09:07 UTC
At the moment when OOME happens we get:
```
org.kframework.utils.errorsystem.KEMException: [Error] Critical: Haskell Backend execution failed with code 137 and produced no output.
```

Front-end should report informative error messages for the following situations:
- kore crashed with out of memory error because it exceeded allocated heap (equivalent to Java OutOfMemoryError)
- kore process was killed by OS, presumably because of low memory (if possible)
- kore process interrupted.
- z3 process interrupted.

This will help debugging memory issues on Jenkins. Also will help distinguishing memory issues from other issues. Cases 1 and 4 can be communicated to front-end via return code.

Front-end should also end with specific error codes in such cases, that can be used by wrapper script to print diagnostics information, like free system memory.

**Comment by ttuegel** [comment] 2020-06-26 10:20
Duplicate of #1929.

**Closed by ttuegel** 2020-06-26 10:20 UTC
