### ISSUE TITLE
Element appears multipletimes in path condition

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#2185] opened 2020-10-09 14:19 UTC
Look at firs failing test here: https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/erc20-verification/detail/PR-150/8/pipeline

```
#And
  #Not ( {
    ?ACCT
  #Equals
    #newAddr ( ?ACCT , 1 )
  } )
#And
  #Not ( {
    ?ACCT
  #Equals
    #newAddr ( ?ACCT , 1 )
  } )
...
```

**Comment by ttuegel** [comment] 2020-10-09 14:56
Duplicate of #1442.

**Closed by ttuegel** 2020-10-09 14:56 UTC
