### ISSUE TITLE
Simplification rule for in_keys breaks map ceil

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#2384] opened 2021-02-04 10:57 UTC
Adding a simplification rule for in_keys results in an incorrect ceil for the initial configuration. This uses the haskell backend at commit `c4278195b46c4c9e584582eff4d7e700afe661e2`.

To reproduce:
tmp.k
```k
module TMP
  imports BOOL
  imports INT
  imports MAP

  syntax KResult ::= Int

  syntax A ::= a(Map) | "b"

  rule X:KItem in_keys((Y:KItem |-> _:KItem M:Map) #as _:Map)
        => X ==K Y orBool X in_keys(M)
    [simplification, label(xyzzy)]

  rule a(M:Map) => b
    requires 3 in_keys(M)

endmodule
```
tmp_proof.k
```
module TMP-PROOF
  imports TMP

  claim a(1 |-> 1 2 |-> 2 3 |-> 3 M:Map) => b
endmodule
```
Run this:
```sh
kompile tmp.k --backend haskell && kprove tmp-proof.k --debugger --debug-script kast.kscript
```
Then, in the repl, just run `konfig`. It should show this:
```
  <k>
    a ( 1 |-> 1
    2 |-> 2
    3 |-> 3
    M ) ~> _DotVar1 ~> .
  </k>
#And
  {
    false
  #Equals
    1 in_keys ( M )
  }
#And
  {
    false
  #Equals
    2 in_keys ( M )
  }
```
Note that `false #Equals 3 in_keys(M)` is missing.

**Comment by ttuegel** [comment] 2021-02-04 16:56
There are two strange things going on here:

1. The frontend provides rules for `in_keys`; that simplification rule shouldn't be necessary.
2. I have traced the application of that rule, and it doesn't get applied to any "interesting" terms, i.e. any terms that would explain the missing side condition.

**Comment by virgil-serbanuta** [comment] 2021-03-02 20:19
I have just observed a strange thing:

The frontend automatically generates axiom below that, after some thinking, is weird, but is likely to be correct. 
```
  axiom{R,Q0} \implies{R} (
    \top{R}(),
    \and{R} (
      \equals{Q0,R} (
        \ceil{SortMap{}, Q0}(
          Lbl'Unds'Map'Unds'{}(Lbl'UndsPipe'-'-GT-Unds'{}(@VarK0:SortKItem{}, @VarK1:SortKItem{}), @VarRest:SortMap{})
        ),
        \and{Q0}(
          \equals{SortBool{}, Q0}(
            Lbl'Unds'in'Unds'keys'LParUndsRParUnds'MAP'Unds'Bool'Unds'KItem'Unds'Map{}(@VarK0:SortKItem{}, @VarRest:SortMap{}),
            \dv{SortBool{}}("false")
          ),
          \and{Q0}(
            \top{Q0}(),
            \ceil{SortKItem{}, Q0}(@VarK1:SortKItem{})
          )
        )
      ),
      \top{R}()))
```

However, if I also add
```
  rule #Ceil(@M:Map (@K:KItem |-> @V:KItem))
      =>  {(@K in_keys(@M)) #Equals false}
          #And #Ceil(@M)
          #And #Ceil(@K)
          #And #Ceil(@V)
    [anywhere, simplification(20)]
```
the error seems to go away.

**Comment by MirceaS** [comment] 2021-03-05 00:54
@virgil-serbanuta by error here do you mean the unusual configuration observed in kore-repl? Because there's no actual error thrown anywhere as far as I can tell...

**Comment by virgil-serbanuta** [comment] 2021-03-05 11:00
Yes, I meant that unusual configuration (I would call it "wrong", not "unusual"). Sorry for not being precise, by "error" I meant something like "wrong behaviour", not "outputs an error message".

BTW, in order to keep the example small, this bug is visible only in the repl. If you want to reproduce the bug using kore-exec, use this tmp.k file:
```
module TMP
  imports BOOL
  imports INT
  imports MAP

  syntax KResult ::= Int

  syntax A ::= a(Map) | "b"

  rule X:KItem in_keys((Y:KItem |-> _:KItem M:Map) #as _:Map)
        => X ==K Y orBool X in_keys(M)
    [simplification, label(xyzzy)]

  rule a(M:Map) => f(M)

  syntax A ::= f(Map)  [function, functional]
  rule f(_:KItem |-> _:KItem M:Map) => f(M)
    [simplification(10)]
  rule f(M:Map) => b
    requires 3 in_keys(M)
    [simplification(20)]
  rule f(M:Map) => b
    requires notBool 3 in_keys(M)
    [simplification(20)]

endmodule
```

**Comment by MirceaS** [comment] 2021-03-05 13:07
@virgil-serbanuta I think I figured out what was wrong. I think the issue is with the rule you originally introduced:
```
rule X:KItem in_keys((Y:KItem |-> _:KItem M:Map) #as _:Map)
        => X ==K Y orBool X in_keys(M)
    [simplification, label(xyzzy)]
```
I'm not sure this rule is really sound because it simplifies terms that may be `Bottom` into terms that are no longer `Bottom`.
Take the following example for instance:
`2 in_keys (3->3 3->3)`
Normally this should simplify to `Bottom` as `3->3 3->3` is not a valid map but using your rule, this simplifies to `2 ==K 3 orBool 2 in_keys (3->3)` which simplifies to the boolean `false`.
In particular, why the condition for 3 is missing seems to be because the simplifier reduces `2 in_keys (3->3 M)` to `2 in_keys (M)` using your rule.

**Comment by ttuegel** [comment] 2021-03-05 15:10
This is a symptom of #2425.

**Comment by MirceaS** [comment] 2021-03-10 17:08
This was fixed by https://github.com/kframework/kore/pull/2392

**Closed by MirceaS** 2021-03-10 17:08 UTC
Labels: appetite: S, blocked, type: investigation
