### ISSUE TITLE
Proof stuck on infeasible state

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1665] opened 2020-03-11 22:55 UTC
kprove failed to prove [process-slots-base1-spec](https://github.com/runtimeverification/beacon-chain-verification/blob/master/dynamic/process-slots-base1-spec.k), outputing the following stuck term, which is clearly bottom:
```
  ( #Forall x . #Ceil ( DotVar2 x ) )
#And
  #Not ( ( #Forall x . #Ceil ( DotVar2 x ) )
  #And
    #Not ( {
      Slot
    #Equals
      Slot +Int 1
    } ) )
...
```

To reproduce:
```
$ git clone git@github.com:runtimeverification/beacon-chain-verification.git
$ git checkout 9ec687a7ab0a7fc8748e4861a6d429aeb58761ea
$ cd dynamic
$ make deps
$ make build-static
$ kprove -d .build/defn/static -m VERIFICATION process-slots-base1-spec.k
```

**Comment by daejunpark** [comment] 2020-03-12 03:37
related: https://github.com/kframework/k/issues/1157

**Comment by ttuegel** [comment] 2020-03-26 13:51
An `in_keys` symbol for Map cells was added in kframework/k#1161. We need to:

- [ ] Add axioms for `in_keys` to `domains.k`.
- [ ] Add `\ceil` axioms for Map to `domains.k` in terms of `in_keys`.
- [ ] Emit axioms for this symbol in `ModuleToKORE`.
- [ ] Emit `\ceil` axioms for Map cells in `ModuleToKORE`.
- [ ] Disable and remove the backend's internal `\ceil(Map)` simplification.

**Comment by ttuegel** [comment] 2020-04-06 14:14
@ana-pantilie We can write the rules for `inKeys` in this `owise` style:

```
rule inKeys(K, K |-> _ M:Map) => true
rule inKeys(K, M:Map) => false [owise]
```

**Comment by ttuegel** [comment] 2020-04-15 10:45
I think we should cut the scope of the solution to this issue because we have exceeded our appetite for it. Instead of relying on simplification rules defined in the frontend to replace the backend's internal simplifier for Maps, I suggest:

- [ ] Merge the open pull request(s?) that define axioms for `in_keys`.
- [ ] Instead of [creating a `\forall` pattern](https://github.com/kframework/kore/blob/master/kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs#L140), apply the [`in_keys` symbol](https://github.com/kframework/kore/blob/master/kore/src/Kore/Builtin/Map/Map.hs#L128) for the relevant sort.

The goal here is to get the Beacon Chain project using the Haskell backend again. It would be nice to define all these rules in K, but it's not essential. We can reconsider defining the rules in the frontend after fixing #1630.

**Comment by ttuegel** [comment] 2020-04-17 10:47
@daejunpark I'm trying to reproduce this again, but I can't build the definition. `make build-static` reports:

```
pandoc --from markdown --to "../deps/pandoc-tangle/tangle.lua" --metadata=code:".k:not(.dynamic):not(.kast)" dynamic-abstract-beacon-chain.md > .build/defn/static/dynamic-abstract-beacon-chain.k
pandoc --from markdown --to "../deps/pandoc-tangle/tangle.lua" --metadata=code:".k:not(.dynamic):not(.kast)" dynamic-abstract-beacon-chain-syntax.md > .build/defn/static/dynamic-abstract-beacon-chain-syntax.k
/nix/store/gs32hc2hw1sy0sxcv2kvnv5lqh0zqcz6-k-5.0.0-f5226463/bin/kompile --debug --main-module DYNAMIC-ABSTRACT-BEACON-CHAIN --backend haskell             \
                 --syntax-module DYNAMIC-ABSTRACT-BEACON-CHAIN-SYNTAX .build/defn/static/dynamic-abstract-beacon-chain.k \
                 --directory .build/defn/static -I .build/defn/static                         \
                 --emit-json                                                        \
                 
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 1 parsing errors.
        at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:126)
        at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:72)
        at org.kframework.kompile.DefinitionParsing.throwExceptionIfThereAreErrors(DefinitionParsing.java:183)
        at org.kframework.kompile.DefinitionParsing.saveCachesAndReportParsingErrors(DefinitionParsing.java:147)
        at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:176)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:163)
        at org.kframework.kompile.Kompile.run(Kompile.java:131)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Inner Parser: Could not find any suitable production for label
totalBalance
        Source(/home/ttuegel/beacon-chain-verification/dynamic/./.build/defn/static/dynamic-abstract-beacon-chain.k)
        Location(225,84,225,96)
make: *** [Makefile:142: .build/defn/static/dynamic-abstract-beacon-chain-kompiled/definition.kore] Error 113
```

**Comment by daejunpark** [comment] 2020-04-17 11:22
@ttuegel Could you please use the specific commit that I mentioned in the reproduction commands above?
```
$ git checkout 9ec687a7ab0a7fc8748e4861a6d429aeb58761ea
```

**Comment by ttuegel** [comment] 2020-04-20 15:44
I have the unparsing error fixed so that the stuck node is now:

```
; kprove -d .build/defn/static -m VERIFICATION process-slots-base1-spec.k
  #Not ( #Not ( {
      Slot
    #Equals
      Slot +Int 1
    } )
  #And
    {
      false
    #Equals
      <slot>
        Slot +Int 1
      </slot> in_keys ( DotVar2 )
    } )
#And
  <T>
    <k>
      processSlot ( ) ~> processEpoch ( ) ~> processSlots ( TargetSlot )
    </k>
    <currentSlot>
      Slot +Int 1
    </currentSlot>
    <states>
      <state>
        <slot>
          Slot
        </slot>
        <validators>
          Vs
        </validators>
        <slashedBalance>
          SB
        </slashedBalance>
        <attested>
          AttestedMap
        </attested>
        <justified>
          JustifiedMap
        </justified>
        <finalized>
          FinalizedMap
        </finalized>
        <lastBlock>
          ( LastBlockSlot , LastBlockID )
        </lastBlock>
        <lastJustified>
          LastJustifiedEpoch
        </lastJustified>
        <lastFinalized>
          LastFinalizedEpoch
        </lastFinalized>
      </state> <state>
        <slot>
          Slot +Int 1
        </slot>
        <validators>
          Vs
        </validators>
        <slashedBalance>
          SB
        </slashedBalance>
        <attested>
          AttestedMap
        </attested>
        <justified>
          JustifiedMap
        </justified>
        <finalized>
          FinalizedMap
        </finalized>
        <lastBlock>
          ( LastBlockSlot , LastBlockID )
        </lastBlock>
        <lastJustified>
          LastJustifiedEpoch
        </lastJustified>
        <lastFinalized>
          LastFinalizedEpoch
        </lastFinalized>
      </state> DotVar2
    </states>
    <blocks>
      DotVar10
    </blocks>
  </T>
#And
  {
    ( Slot +Int 1 ) %Int 4 ==Int 0
  #Equals
    false
  }
#And
  {
    Slot <Int TargetSlot
  #Equals
    true
  }
#And
  {
    false
  #Equals
    <slot>
      Slot
    </slot> in_keys ( DotVar2 )
  }
#And
  {
    true
  #Equals
    LastBlockSlot >=Int 0
  }
#And
  {
    true
  #Equals
    LastFinalizedEpoch >=Int 0
  }
#And
  {
    true
  #Equals
    LastJustifiedEpoch >=Int 0
  }
#And
  {
    true
  #Equals
    Slot +Int 1 ==Int TargetSlot
  }
#And
  {
    true
  #Equals
    Slot >=Int 0
  }
#And
  {
    true
  #Equals
    isValidators ( Vs )
  }
```

This configuration is also `\bottom`, but in a more subtle way. Look at this condition:

```
  #Not ( #Not ( {
      Slot
    #Equals
      Slot +Int 1
    } )
  #And
    {
      false
    #Equals
      <slot>
        Slot +Int 1
      </slot> in_keys ( DotVar2 )
    } )
#And
  ...
```

In particular, this appears negated:

```
{
    false
  #Equals
    <slot>
      Slot +Int 1
    </slot> in_keys ( DotVar2 )
}
```

If that condition does not hold, then the configuration is `\bottom` because `<state><slot>Slot +Int 1</slot> ...</state> DotVar2` appears. Therefore, we need to address #1103 to continue.

**Comment by ttuegel** [comment] 2020-04-30 11:31
With #1757 merged, here is what remains:

- [ ] Add a built-in simplifier for `\equals(false, K1 in_keys (K2 |-> _ M:Map)) => \not \equals(K1, K2) \and \equals(false, K1 in_keys (M:Map))`
- [ ] Disable and remove the built-in `\ceil(concatMap)` simplifier.

**Comment by ttuegel** [comment] 2020-06-02 21:06
The pull request which closed this issue only fixes the unparsing bug which masked the real bug. We must also check, before reporting a "stuck" state, that the state is defined.

**Comment by ttuegel** [comment] 2020-06-04 14:05
This would be fixed by fixing #1412.

**Comment by denis-bogdanas** [comment] 2020-06-18 15:20
Note for reference: proper rules for `#Ceil(#buf)` depend on this issue.

**Comment by ttuegel** [comment] 2020-07-27 14:17
I am re-opening this issue due to [this comment](https://github.com/kframework/kore/issues/1990#issuecomment-663964978)

**Comment by ttuegel** [comment] 2020-07-28 20:44
The comment above actually exposes #2021.

**Closed by ttuegel** 2020-07-28 20:44 UTC
Labels: appetite: S, feature
