### ISSUE TITLE
Minimal proof fails on Haskell backend

### ISSUE THREAD

**Issue by hjorthjort** [kframework/kore#1451] opened 2020-01-18 19:34 UTC
I get a failure with `kore-exec: Quantifying both the term and the predicate probably means that there's
an error somewhere else.`, while the Java backend manages to prove this.

The proof:
```
module FOO
  imports DOMAINS

configuration
  <k> $PGM:P </k>

syntax P ::= "foo" Int Int

rule <k> foo X Y => foo Y X ... </k>
rule <k> foo X Y => X +Int Y +Int 1 ... </k>

endmodule

module FOO-SPEC
  imports FOO


  rule <k> foo X Y => Z ... </k>
    ensures Z >Int X +Int Y

endmodule
```

Run with

```
kompile --main-module FOO foo-spec.k --backend haskell && kprove -m FOO foo-spec.k
```

Full error message:

```
CallStack (from HasCallStack):
  formatExceptionInfo, called at src/Kore/Strategies/Goal.hs:708:14 in kore-0.0.1.0-7aODSKrnRFOEARjmD152VX:Kore.Strategies.Goal

configuration=\and{SortGeneratedTopCell{}}(
    /* term: */
    \exists{SortGeneratedTopCell{}}(
        VarZ:SortInt{},
        /* Created by <toTermLike> at src/Kore/Step/Step.hs:177:18 */
        \and{SortGeneratedTopCell{}}(
            Lbl'-LT-'generatedTop'-GT-'{}(
                Lbl'-LT-'k'-GT-'{}(
                    kseq{}(
                        inj{SortInt{}, SortKItem{}}(VarZ:SortInt{}),
                        VarDotVar1:SortK{}
                    )
                ),
                Lbl'-LT-'generatedCounter'-GT-'{}(VarDotVar00:SortInt{})
            ),
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                Lbl'Unds-GT-'Int'Unds'{}(
                    VarZ:SortInt{},
                    Lbl'UndsPlus'Int'Unds'{}(VarY:SortInt{}, VarX:SortInt{})
                ),
                /* builtin: */ \dv{SortBool{}}("true")
            )
        )
    ),
\and{SortGeneratedTopCell{}}(
    /* predicate: */
    \top{SortGeneratedTopCell{}}(),
    /* substitution: */
    \top{SortGeneratedTopCell{}}()
))
------------------
kore-exec: Quantifying both the term and the predicate probably means that there's
an error somewhere else.
variable=VarZ:SortInt{}
patt=\and{SortGeneratedTopCell{}}(
    /* term: */
    Lbl'-LT-'generatedTop'-GT-'{}(
        Lbl'-LT-'k'-GT-'{}(
            kseq{}(
                inj{SortInt{}, SortKItem{}}(VarZ:SortInt{}),
                VarDotVar1:SortK{}
            )
        ),
        Lbl'-LT-'generatedCounter'-GT-'{}(VarDotVar00:SortInt{})
    ),
\and{SortGeneratedTopCell{}}(
    /* predicate: */
    \equals{SortBool{}, SortGeneratedTopCell{}}(
        Lbl'Unds-GT-'Int'Unds'{}(
            VarZ:SortInt{},
            Lbl'UndsPlus'Int'Unds'{}(VarY:SortInt{}, VarX:SortInt{})
        ),
        /* builtin: */ \dv{SortBool{}}("true")
    ),
    /* substitution: */
    \top{SortGeneratedTopCell{}}()
))

CallStack (from HasCallStack):
  error, called at src/Kore/Step/Simplification/Exists.hs:354:6 in kore-0.0.1.0-7aODSKrnRFOEARjmD152VX:Kore.Step.Simplification.Exists
[Error] Internal: Uncaught exception thrown of type FileNotFoundException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(./.kprove-2020-01-18-16-58-19-763-2e6e6427-1a27-4845-88b0-27cb4e48d528/result.kore
(No such file or directory))
```

**Comment by ttuegel** [comment] 2020-01-21 02:46
I think this is one manifestation of a known limitation to how we currently handle `\exists`, but we should investigate more to be sure.

**Comment by ttuegel** [comment] 2020-01-21 16:40
@traiansf Can you look at this when you have time?

**Comment by traiansf** [comment] 2020-01-22 10:10
I think the exact same issue was discussed on the public [Slack channel](https://riot.im/app/#/room/!MfVXcmpKuyudZHcqil:matrix.org/$1579293981718150SvIjN:matrix.org). The issue is that the `Z` variable in the spec should instead be `?Z` (proofs works fine when using `?Z`). Proving it as-is with the Java backend is unsound :-) because it's not true that it holds for all Zs.  In this issue is proposed that we detect such cases and throw an error (asking people to quantify them existentially: https://github.com/kframework/k/issues/1046

@hjorthjort could you please confirm and close the issue, if so?

**Comment by hjorthjort** [comment] 2020-01-22 10:15
So I think I have been confused about this. When exactly is the `?` used, and what would be the interpretation of the claim above when we use `Z` instead of `?Z`?

I haven't used the `?` in proofs before. Is it perhaps the case that the Java backend actually treats this claim differently, rather than it being a bug?

**Comment by hjorthjort** [comment] 2020-01-22 10:19
For example, this proof:
https://github.com/runtimeverification/verified-smart-contracts/blob/master/erc20/zeppelin/zeppelin-erc20-spec.ini#L82

Wouldn't it also need `?M2` for it to be true?

**Comment by hjorthjort** [comment] 2020-01-22 12:14
So after playing around a bit, my current understanding is when a variable only occurs on the right-hand side of a claim it is:

1. universally quantified if it does *not* start with `?`, so the interpretation is that any value can be put in its place;
2. existentially quantified when it starts with `?`, so the interpretation is that there is always some value that can be put in its place.

However, then proof above (https://github.com/runtimeverification/verified-smart-contracts/blob/master/erc20/zeppelin/zeppelin-erc20-spec.ini#L82) as well as the KWasm reverse bytes spec (https://github.com/kframework/wasm-semantics/blob/master/tests/proofs/wrc20-spec.k#L41) should be using existential quantification.

**Comment by traiansf** [comment] 2020-01-22 13:00
Yes, I would say that this would be the current assumption.  @ehildenb @daejunpark what would you say?

However, if we so far assumed that variables appearing only in the RHS of claims are to be existentially quantified, and this is already widespread in proofs, then we could clarify this somewhere  and alter the frontend to existentially quantify them before sending them to the KORE prover.

**Comment by ehildenb** [comment] 2020-01-22 14:08
I like having the option to select universal or existential quantification, and `?` variables being existentially quantified makes sense with how I think of them.

@daejunpark will have to speak to the theoretical side for his understanding. But one thing I'm fairly certain of is that changing over all the proofs shouldn't be too difficult, so we shouldn't shy away from doing that. If it's unsound what the Java backend has been doing, we shouldn't do the same.

**Comment by daejunpark** [comment] 2020-01-22 14:23
I have no problem with changing proofs. Indeed initially the java backend
also had required to use ? variables for RHS only ones. But at some point,
it started to treat both the same.

Generating errors or warnings for the use of non ? variables will also be
necessary, as it is not common and likely a mistake.

BTW, could you please remind me with a specific example spec when the
universally quantified RHS only variables are really needed? I think I had
one before, but cannot remember now. Would be good to have that in some
document.

**Comment by traiansf** [comment] 2020-01-22 14:40
> BTW, could you please remind me with a specific example spec when the
universally quantified RHS only variables are really needed? I think I had
one before, but cannot remember now. Would be good to have that in some
document.

I don't know of any concrete example where that would be useful; the only example I can think of would be if wanting to prove that all possible values of a certain sort are reachable from the initial configuration.

**Comment by hjorthjort** [comment] 2020-01-22 14:45
> > BTW, could you please remind me with a specific example spec when the
> > universally quantified RHS only variables are really needed? I think I had
> > one before, but cannot remember now. Would be good to have that in some
> > document.
> 
> I don't know of any concrete example where that would be useful; the only example I can think of would be if wanting to prove that all possible values of a certain sort are reachable from the initial configuration.

If so, it should ideally be possible to restrict the quantification with side conditions, i.e., make sure that there is a way to put a filtering implication in the universal quantifier. For example something like:

```
rule <k> foo => X ... </k>
  requires X >Int 0
```
where the intent is that foo will eventually rewrite to any and all positive integers.

**Comment by traiansf** [comment] 2020-01-22 14:49
> ```
> rule <k> foo => X ... </k>
>   requires X >Int 0
> ```
> 
> where the intent is that foo will eventually rewrite to any and all positive integers.

Yes, that should work. Note, however, that in an all-path semantics, something like this is highly improbable, unless you have a cycle going through all instances of `X`, because all-path requires that each instance of `X` is reachable on each path from the initial configuration, including those on which you reach other instances. @xc93 can you please confirm?

**Comment by hjorthjort** [comment] 2020-01-22 14:51
> > ```
> > rule <k> foo => X ... </k>
> >   requires X >Int 0
> > ```
> > 
> > 
> > where the intent is that foo will eventually rewrite to any and all positive integers.
> 
> Yes, that should work. Note, however, that in an all-path semantics, something like this is highly improbable, unless you have a cycle going through all instances of `X`, because all-path requires that each instance of `X` is reachable on each path from the initial configuration, including those on which you reach other instances. @xc93 can you please confirm?

Yes, this is a silly example, but I was thinking about something like a semantics wth the rules

```
rule <k> foo => 1 ... </k>
rule <k> X:Int => X +Int 1 ... </k>
```

**Closed** 2020-01-31 15:11 UTC
Labels: appetite: S, bug, investigate
