### ISSUE TITLE
REPL option konfig-d does not work with redirection

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1636] opened 2020-03-05 18:56 UTC
```
Kore (591)> konfig-d /mnt/d/evm-semantics/.build/defn/symb-test > /mnt/d/logs/kofig591.log
Config at node 591 is:
[Error] Critical: Does not exist or not a directory: /mnt/d/evm-semantics/./x
```

**Comment by ttuegel** [comment] 2020-07-21 18:52
Duplicate of #1960.

**Closed by ttuegel** 2020-07-21 18:52 UTC
