### ISSUE TITLE
Predicate simplification loop limit

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#2921] opened 2021-11-19 09:59 UTC
Sorry I didn't extract a simpler example, but I'm working from my Mac and my current setup is somewhat broken, so I can't do that in a reasonable way (e.g. kprint does not work, but that's not the only issue). I'll try to do that in a future comment.

FWIW, I'm currently working on this proof, so it's not supposed to pass.

Bug report: [predicate-loop.tar.gz](https://github.com/kframework/kore/files/7561862/predicate-loop.tar.gz)

The warning I receive:
```
Kore version 0.55.0.0
Git:
  revision:     03694d9ae4d99c76de42d49266484939b18ef6d4 (dirty)
  branch:       master
  last commit:  Tue Oct 19 09:10:32 2021 -0500
kore-exec: [3114243] Warning (WarnUnsimplifiedPredicate):
    (InfoReachability) while simplifying the claim:
    (DebugAttemptEquation) while applying equation at /private/var/tmp/_bazel_virgil/7ebb50144cfccb48519cef812dffd979/sandbox/darwin-sandbox/86/execroot/__main__/protocol-correctness/symbolic-map/typed-map.k:61:10-65:10:
    Predicate not simplified after 4 rounds.
    Original predicate:
        /* Spa */
        \not{_}(
            /* Sfa */
            \not{_}(
                /* Spa */
                \exists{_}(
                    EquationVar'Unds'6:SortCastable{},
                    /* Spa */
                    \exists{_}(
                        EquationVar'Unds'7:SortTypedMapEntryCellMap{},
                        /* Spa */
                        \and{_}(
                            /* Spa */
                            \ceil{SortCastable{}, _}(
                                /* Fl Fn D Sfa */ ConfigVarKey:SortCastable{}
                            ),
                            /* Spa */
                            \and{_}(
                                /* Spa */
                                \equals{SortTypedMapEntryCellMap{}, _}(
                                    /* Fn Spa */
                                    /* InternalMap: */ Lbl'Unds'TypedMapEntryCellMap'Unds'{}(
                                        /* element: */ LblTypedMapEntryCellMapItem{}(
                                            /* Fl Fn D Spa */
                                            Lbl'-LT-'typed-map-key'-GT-'{}(
                                                /* Fl Fn D Sfa */
                                                ConfigVarKey:SortCastable{}
                                            ),
                                            /* Fl Fn D Spa */
                                            Lbl'-LT-'typed-map-entry'-GT-'{}(
                                                /* Fl Fn D Spa */
                                                Lbl'-LT-'typed-map-key'-GT-'{}(
                                                    /* Fl Fn D Sfa */
                                                    ConfigVarKey:SortCastable{}
                                                ),
                                                /* Fl Fn D Sfa */
                                                Lbl'-LT-'typed-map-value'-GT-'{}(
                                                    /* Fl Fn D Sfa */
                                                    EquationVar'Unds'6:SortCastable{}
                                                )
                                            )
                                        ),
                                        /* opaque child: */ /* Fl Fn D Sfa */
                                        EquationVar'Unds'7:SortTypedMapEntryCellMap{}
                                    ),
                                    /* Fn Sfa */
                                    /* InternalMap: */ Lbl'Unds'TypedMapEntryCellMap'Unds'{}(
                                        /* element: */ LblTypedMapEntryCellMapItem{}(
                                            /* Fl Fn D Sfa */
                                            Lbl'-LT-'typed-map-key'-GT-'{}(
                                                /* Fl Fn D Sfa */
                                                ConfigVarKey:SortCastable{}
                                            ),
                                            /* Fl Fn D Sfa */
                                            Lbl'-LT-'typed-map-entry'-GT-'{}(
                                                /* Fl Fn D Sfa */
                                                Lbl'-LT-'typed-map-key'-GT-'{}(
                                                    /* Fl Fn D Sfa */
                                                    ConfigVarKey:SortCastable{}
                                                ),
                                                /* Fl Fn D Sfa */
                                                Lbl'-LT-'typed-map-value'-GT-'{}(
                                                    /* Fl Fn D Sfa */
                                                    ConfigVarValue:SortCastable{}
                                                )
                                            )
                                        ),
                                        /* opaque child: */ /* Fl Fn D Sfa */
                                        ConfigVar'Unds'DotVar2:SortTypedMapEntryCellMap{}
                                    )
                                ),
                                /* Spa */
                                \and{_}(
                                    /* Spa */
                                    \equals{SortCastable{}, _}(
                                        /* Fl Fn D Sfa */
                                        ConfigVarKey:SortCastable{},
                                        /* Fl Fn D Sfa */
                                        ConfigVarKey:SortCastable{}
                                    ),
                                    /* Spa */
                                    \not{_}(
                                        /* Spa */
                                        \exists{_}(
                                            Rulex:SortTypedMapEntryCell{},
                                            /* Spa */
                                            \not{_}(
                                                /* Spa */
                                                \ceil{SortTypedMapEntryCellMap{}, _}(
                                                    /* Fn Spa */
                                                    /* InternalMap: */ Lbl'Unds'TypedMapEntryCellMap'Unds'{}(
                                                        /* element: */ LblTypedMapEntryCellMapItem{}(
                                                            /* Fl Fn D Spa */
                                                            Lbl'-LT-'typed-map-key'-GT-'{}(
                                                                /* Fl Fn D Sfa */
                                                                ConfigVarKey:SortCastable{}
                                                            ),
                                                            /* Fl Fn D Sfa */
                                                            Rulex:SortTypedMapEntryCell{}
                                                        ),
                                                        /* opaque child: */ /* Fl Fn D Sfa */
                                                        EquationVar'Unds'7:SortTypedMapEntryCellMap{}
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    Output after 4 rounds:
        /* Sfa */
        \not{_}(
            /* Spa */
            \exists{_}(
                Rulex:SortTypedMapEntryCell{},
                /* Sfa */
                \not{_}(
                    /* Sfa */
                    \ceil{SortTypedMapEntryCellMap{}, _}(
                        /* Fn Spa */
                        /* InternalMap: */ Lbl'Unds'TypedMapEntryCellMap'Unds'{}(
                            /* element: */ LblTypedMapEntryCellMapItem{}(
                                /* Fl Fn D Sfa */
                                Lbl'-LT-'typed-map-key'-GT-'{}(
                                    /* Fl Fn D Sfa */
                                    ConfigVarKey:SortCastable{}
                                ),
                                /* Fl Fn D Sfa */ Rulex:SortTypedMapEntryCell{}
                            ),
                            /* opaque child: */ /* Fl Fn D Sfa */
                            ConfigVar'Unds'DotVar2:SortTypedMapEntryCellMap{}
                        )
                    )
                )
            )
        )
```

**Comment by ana-pantilie** [comment] 2021-11-19 10:42
Thanks Virgil, this is interesting. We'll need to see if removing the limit induces looping behavior, maybe it's just the case that it eventually gets fully simplified after more iterations. If it's looping, then we can study this example to get a better idea of what exactly is looping inside the simplifier.

**Comment by ana-pantilie** [comment] 2021-12-02 15:09
@dopamane tried to reproduce this but failed, @andreiburdusa could you take a look as well?

**Comment by andreiburdusa** [comment] 2021-12-08 11:01
I also failed reproducing the error. All I get is some `WarnFunctionWithoutEvaluators` warnings

**Comment by ana-pantilie** [comment] 2021-12-08 11:04
I'm going to close this since we can't reproduce it.

**Closed by ana-pantilie** 2021-12-08 11:04 UTC
Labels: type: bug, type: investigation
