### ISSUE TITLE
Eliminate branch where argument of the configuration is undefined.

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1101] opened 2019-10-11 15:09 UTC
When proving WASM memory-spec.k, I met a branch has the following condition:
```  #Not ( #Ceil ( <memInst>
      <mAddr>
        MEMADDR
      </mAddr>
      <mmax>
        DotVar50
      </mmax>
      <msize>
        SIZE
      </msize>
      <mdata>
        ByteMap <| BM0 |>
      </mdata>
    </memInst> DotVar4 )
  #And
    #Ceil ( <moduleInst>
      <modIdx>
        CUR
      </modIdx>
      <exports>
        _110
      </exports>
      <typeIds>
        _120
      </typeIds>
      <types>
        _130
      </types>
      <nextTypeIdx>
        _140
      </nextTypeIdx>
      <funcIds>
        _150
      </funcIds>
      <funcAddrs>
        _160
      </funcAddrs>
      <nextFuncIdx>
        _170
      </nextFuncIdx>
      <tabIds>
        _180
      </tabIds>
      <tabAddrs>
        _190
      </tabAddrs>
      <memIds>
        _200
      </memIds>
      <memAddrs>
        0 |-> MEMADDR:Int
      </memAddrs>
      <globIds>
        _210
      </globIds>
      <globalAddrs>
        _220
      </globalAddrs>
      <nextGlobIdx>
        _230
      </nextGlobIdx>
    </moduleInst> DotVar7 ) )
```.
This condition means that some arguments of of the configuration is undefined and thus the whole configuration is bottom. This branch should be eliminated through simplification.

**Comment by yzhang90** [comment] 2019-10-11 15:25
whole configuration:
```
  #Not ( #Ceil ( <memInst>
      <mAddr>
        MEMADDR
      </mAddr>
      <mmax>
        DotVar50
      </mmax>
      <msize>
        SIZE
      </msize>
      <mdata>
        ByteMap <| BM0 |>
      </mdata>
    </memInst> DotVar4 )
  #And
    #Ceil ( <moduleInst>
      <modIdx>
        CUR
      </modIdx>
      <exports>
        _110
      </exports>
      <typeIds>
        _120
      </typeIds>
      <types>
        _130
      </types>
      <nextTypeIdx>
        _140
      </nextTypeIdx>
      <funcIds>
        _150
      </funcIds>
      <funcAddrs>
        _160
      </funcAddrs>
      <nextFuncIdx>
        _170
      </nextFuncIdx>
      <tabIds>
        _180
      </tabIds>
      <tabAddrs>
        _190
      </tabAddrs>
      <memIds>
        _200
      </memIds>
      <memAddrs>
        0 |-> MEMADDR:Int
      </memAddrs>
      <globIds>
        _210
      </globIds>
      <globalAddrs>
        _220
      </globalAddrs>
      <nextGlobIdx>
        _230
      </nextGlobIdx>
    </moduleInst> DotVar7 ) )
#And
  #True
#And
  <wasm>
    <k>
      ( ITYPE . store ( i32 . const ADDR )  ( ITYPE . load ( i32 . const ADDR )  .EmptyStmts )  .EmptyStmts ) ~> DotVar2
    </k>
    <valstack>
      _240
    </valstack>
    <curFrame>
      <locals>
        _70
      </locals>
      <localIds>
        _80
      </localIds>
      <curModIdx>
        CUR:Int
      </curModIdx>
      <labelDepth>
        _90
      </labelDepth>
      <labelIds>
        _100
      </labelIds>
    </curFrame>
    <moduleRegistry>
      _250
    </moduleRegistry>
    <moduleIds>
      _260
    </moduleIds>
    <moduleInstances>
      <moduleInst>
        <modIdx>
          CUR
        </modIdx>
        <exports>
          _110
        </exports>
        <typeIds>
          _120
        </typeIds>
        <types>
          _130
        </types>
        <nextTypeIdx>
          _140
        </nextTypeIdx>
        <funcIds>
          _150
        </funcIds>
        <funcAddrs>
          _160
        </funcAddrs>
        <nextFuncIdx>
          _170
        </nextFuncIdx>
        <tabIds>
          _180
        </tabIds>
        <tabAddrs>
          _190
        </tabAddrs>
        <memIds>
          _200
        </memIds>
        <memAddrs>
          0 |-> MEMADDR:Int
        </memAddrs>
        <globIds>
          _210
        </globIds>
        <globalAddrs>
          _220
        </globalAddrs>
        <nextGlobIdx>
          _230
        </nextGlobIdx>
      </moduleInst> DotVar7
    </moduleInstances>
    <nextModuleIdx>
      _270
    </nextModuleIdx>
    <mainStore>
      <funcs>
        _00
      </funcs>
      <nextFuncAddr>
        _10
      </nextFuncAddr>
      <tabs>
        _20
      </tabs>
      <nextTabAddr>
        _30
      </nextTabAddr>
      <mems>
        <memInst>
          <mAddr>
            MEMADDR
          </mAddr>
          <mmax>
            DotVar50
          </mmax>
          <msize>
            SIZE
          </msize>
          <mdata>
            ByteMap <| BM0 |>
          </mdata>
        </memInst> DotVar4
      </mems>
      <nextMemAddr>
        _40
      </nextMemAddr>
      <globals>
        _50
      </globals>
      <nextGlobAddr>
        _60
      </nextGlobAddr>
    </mainStore>
    <deterministicMemoryGrowth>
      _280
    </deterministicMemoryGrowth>
    <nextFreshId>
      _290
    </nextFreshId>
  </wasm>
#And
  {
    true
  #Equals
    ADDR modInt 4294967296 +Int #numBytes ( ITYPE ) <=Int SIZE *Int 65536 andBool #isByteMap ( ByteMap <| BM0 |> )
  }
```

**Comment by yzhang90** [comment] 2019-10-11 18:39
see #1103

**Comment by ttuegel** [comment] 2019-10-21 19:19
Duplicate of: #1103

**Closed by ttuegel** 2019-10-21 19:19 UTC
