### ISSUE TITLE
Map is not normalized when startup

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1027] opened 2019-09-27 15:30 UTC
I'm debugging the memory-spec.k in WASM. In the very beginning, I print the config of node 0:
```
...
            Lbl'-LT-'moduleInstances'-GT-'{}(
                Lbl'Unds'ModuleInstCellMap'Unds'{}(
                    VarMODULEINSTS:SortModuleInstCellMap{},
                    LblModuleInstCellMapItem{}(
                        Lbl'-LT-'modIdx'-GT-'{}(VarCUR:SortInt{}),
                        Lbl'-LT-'moduleInst'-GT-'{}(
                            Lbl'-LT-'modIdx'-GT-'{}(VarCUR:SortInt{}),
                            Var'Unds'0:SortExportsCell{},
                            Var'Unds'1:SortTypeIdsCell{},
                            Var'Unds'2:SortTypesCell{},
                            Var'Unds'3:SortNextTypeIdxCell{},
                            Var'Unds'4:SortFuncIdsCell{},
                            Var'Unds'5:SortFuncAddrsCell{},
                            Var'Unds'6:SortNextFuncIdxCell{},
                            Var'Unds'7:SortTabIdsCell{},
                            Var'Unds'8:SortTabAddrsCell{},
                            Var'Unds'9:SortMemIdsCell{},
                            Var'Unds'10:SortMemAddrsCell{},
                            Var'Unds'11:SortGlobIdsCell{},
                            Var'Unds'12:SortGlobalAddrsCell{},
                            Var'Unds'13:SortNextGlobIdxCell{}
                        )
                    )
                )
            ),
...
```
The `ModuleInstCellMap` doesn't put symbolic key value pair before the variable `VarMODULEINSTS`

**Comment by ttuegel** [comment] 2019-09-27 17:05
We internalize the rules from the definition module [at startup](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/Data.hs#L207), but we must not do this for the verification module.

**Comment by virgil-serbanuta** [comment] 2019-10-04 12:55
@yzhang90 I cannot reproduce this, I think it was fixed by https://github.com/kframework/kore/pull/1047, could you confirm?

**Closed** 2019-10-08 14:15 UTC
Labels: bug
