### ISSUE TITLE
Remove trivial branches when simplifying claims at startup

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1071] opened 2019-10-07 19:21 UTC
I'm debugging the `https://github.com/kframework/wasm-semantics/blob/memory-spec/tests/proofs/memory-spec.k` under memory-spec branch in wasm-semantics.
I found that in `0449856d84f82eea8df31f8510ed5ed1066cdb36`, after simplifying the LHS, it split the original claim into 2. One of them is
```
  ( #Ceil ( ADDR modInt 4294967296 )
    #And
      {
        EA
      #Equals
        ADDR modInt 4294967296
      }
  #Implies
    {
      true
    #Equals
      EA +Int #numBytes ( ITYPE ) <=Int SIZE *Int 65536 andBool #isByteMap ( ByteMap <| BM0 |> )
    } )
#And
  #Ceil ( ADDR modInt 4294967296 )
#And
  #Not ( #Ceil ( ADDR modInt 4294967296 )
  #And
    #Not ( #Ceil ( ADDR modInt 4294967296 )
    #And
      {
        EA
      #Equals
        ADDR modInt 4294967296
      } ) )
#And
  #Not ( #Ceil ( ADDR modInt 4294967296 )
  #And
    {
      EA
    #Equals
      ADDR modInt 4294967296
    } )
```

- [x] `#Ceil (... modInt ...)` is simplifiable.
- [ ] We should simplify the predicate to remove trivial branches of the proof.

**Comment by yzhang90** [comment] 2019-10-08 00:37
We saw similar not(a) #and not(not(a)) in #1060

**Comment by ttuegel** [comment] 2019-10-21 19:20
Duplicate of #1103.

**Comment by ana-pantilie** [comment] 2019-10-24 10:36
I think 1. is fixed on the latest `kore` master, could you please double check?

**Comment by ttuegel** [comment] 2019-10-24 21:28
Yes, the `Ceil(... modInt ...)` problem is definitely fixed.

**Closed** 2019-10-28 11:50 UTC
