### ISSUE TITLE
ERC20 verifier execution stuck with `#Not ( #Ceil...`

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#2061] opened 2020-08-12 15:45 UTC
https://github.com/runtimeverification/erc20-verification/pull/122
Uses KEVM-master.

Finished execution (same code as above, just different PR): https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/erc20-verification/detail/PR-121/2/pipeline/

The issue is caused by some rules not being marked `[concrete]`. This presumably fixes it: https://github.com/kframework/evm-semantics/commit/ad6a78688d6a34d856f18c8cd8304684b3b7fc2a

**Comment by ttuegel** [comment] 2020-08-18 19:04
This is a duplicate of #2021.

**Closed by ttuegel** 2020-08-18 19:04 UTC
Labels: bug, investigate
